language: node_js
node_js:
  - "8"
script: "npm test -- --single-run --browsers Firefox"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache: yarn
addons:
  firefox: latest
